import React from 'react';
import '../style/Experience.css';

class Experience extends React.Component {

    render() {
        return(
            <div className="full-wrap">
                <div className="first-entry" align="center">
                        <div className="jobtitle">Software Engineering Intern - Schweitzer Engineering Laboratories</div>
                        <div className="timeline">01/01/2018 - Present | 2 Years</div>
                        <div className="duties">
                            <ul className="unstyled">
                                <li>
                                    Implemented a python module to automate the attenuation levels applied over an RF 
                                    connection. This was integrated into the R&D department’s testing framework.
                                </li>
                                <li>
                                    Created web application to display documentation generated by a Jenkins build
                                </li>
                                <li>
                                    Refer to review for duties
                                </li>
                            </ul>
                        </div>
                        <label>Letters of Recommendation: </label>
                        <div className="reference"  target="_blank"><a href="">Kenji Yamamoto - Engineering Manager</a></div>
                        <div className="reference"  target="_blank"><a href="">Rohan Schroff - Supervisor / Mentor</a></div>
                        <br></br><br></br>
                        <div className="line"></div>
                    </div>
                    <p></p>
                    <div className="pad-entry" align="center">
                        <div className="jobtitle">Research Assistant - Integrative Physiology & Neuroscience – WSU</div>
                        <div className="timeline">02/2017 – 08/2017 | 6 Months</div>
                        <div className="duties">
                            <ul className="unstyled">
                                <li>
                                    Studied the effects the Solitary Nucleus has on appetite.
                                </li>
                                <li>
                                    The highlight of my time at Dr. Ritter's lab was the closely monitored and guided surgery 
                                    I performed on one of the subjects, <br></br>where I implanted a cannula into the 4th ventricle to 
                                    be used for direct injections.
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div className="pad-entry" align="center">
                        <br></br><br></br>
                        <div className="line"></div>
                        <div className="jobtitle">Completed Courses:</div>
                        <div className="classes">
                            <ul className="class-list">
                                <li>
                                    Web Development <span className="lang"> ( JavaScript, HTML, CSS, React, Node.js, MongoDB )</span>
                                </li>
                                <li>
                                    Software Engineering Principles <span className="lang"> ( HTML, CSS, JavaScript, jQuery )</span>
                                </li>
                                <li>
                                    Database Systems <span className="lang"> ( SQL, C# )</span>
                                </li>
                                <li>
                                    Human-Computer Interaction | Proper UI Design
                                </li>
                                <li>
                                    Data Mining <span className="lang"> ( Python )</span>
                                </li>
                                <li>
                                    Software Design & Architecture <span className="lang"> ( C# )</span>
                                </li>
                                <li>
                                    Object-Oriented Software Principles <span className="lang"> ( C# )</span>
                                </li>
                                <li>
                                    Programming Language Design <span className="lang"> ( ML, Python, Java )</span>
                                </li>
                                <li>
                                    Advanced Data Structures <span className="lang"> ( C, C++ )</span>
                                </li>
                                <li>
                                    Algorithm Design & Analysis <span className="lang"> ( Python )</span>
                                </li>
                                <li>
                                    Automata and Formal Languages <span className="lang"> ( MIPS )</span>
                                </li>
                                <li>
                                    Systems Programming <span className="lang"> ( C )</span>
                                </li>
                                <li>
                                    Operating Systems & Computer Architecture <span className="lang"> ( C )</span>
                                </li>
                            </ul>
                            <a href="get from server" target="_blank">View Full Transcript</a>
                        </div>
                    </div>
                </div>
        );
    }
}

export default Experience;