import React from 'react';
import '../style/Experience.css';

class Experience extends React.Component {

    render() {
        return(
            <div className="full-wrap parent">
                <div className="entry" align="center">
                        <div className="jobtitle">Software Engineering Intern - Schweitzer Engineering Laboratories</div>
                        <div className="timeline">01/01/2018 - Present | 2 Years</div>
                        <div className="duties">
                            <ul>
                                <li>
                                    Implemented a python module to automate the attenuation levels applied over an RF 
                                    connection. This was integrated into the R&D department’s testing framework.
                                </li>
                                <li>
                                    Created web application to display documentation generated by a Jenkins build
                                </li>
                                <li>
                                    Refer to review for duties
                                </li>
                            </ul>
                        </div>
                        <label>Letters of Recommendation: </label>
                        <div className="reference"><a href="">Kenji Yamamoto - Engineering Manager</a></div>
                        <div className="reference"><a href="">Rohan Schroff - Supervisor / Mentor</a></div>
                        <br></br><br></br>
                        <div className="line"></div>
                    </div>
                    <p></p>
                    <div className="entry" align="center">
                        <div className="jobtitle">Research Assistant - Integrative Physiology & Neuroscience – WSU</div>
                        <div className="timeline">02/2017 – 08/2017 | 6 Months</div>
                        <div className="duties">
                            <ul>
                                <li>
                                    Studied the effects the Solitary Nucleus has on appetite.
                                </li>
                                <li>
                                    The highlight of my time at Dr. Ritter's lab was the closely monitored and guided surgery 
                                    I performed on one of the subjects, <br></br>where I implanted a cannula into the 4th ventricle to 
                                    be used for direct injections.
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
        );
    }

}

export default Experience;